# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPkth2ofFzMzy3avufTOVJAKpMBx8n2K
"""

import pandas as pd

df = pd.read_csv('consumo_hotel_mensal.csv')

# Simulação do sensor
presenca = False
quarto_ocupado = False
horario = 23  # 23h
ar_condicionado = True
iluminacao = True

print("Simulação IoT")

# Regra 1: Quarto desocupado -> tudo desliga
if not quarto_ocupado:
    ar_condicionado = False
    iluminacao = False
    print("Quarto vazio: AC e iluminação desligados.")

# Regra 2: Quarto ocupado mas sem presença -> Modo econômico
elif quarto_ocupado and not presenca:
    ar_condicionado = True
    print("Quarto ocupado sem presença: AC em modo ECO.")

# Regra 3: Presença detectada -> Conforto total
elif quarto_ocupado and presenca:
    ar_condicionado = True
    iluminacao = True
    print("Presença detectada: Conforto mantido.")

# Regra 4: Iluminação noturna reduzida
if horario >= 0 and horario <= 5:
    iluminacao = False
    print("Horário noturno: iluminação reduzida.")

print(f"Estado final: AC={ar_condicionado}, Luz={iluminacao}")